---
driver:
  name: vagrant
  require_chef_omnibus: 12.5.1
provisioner:
  name: chef_zero

platforms:
- name: windows-2012
  driver_config:
    box: opentable/win-2012r2-standard-amd64-nocm

suites:
  - name: default
    run_list:
      - recipe[seven_zip]
